import { Roboto } from "next/font/google";
import "./globals.css";
import Nav from "@/components/shared/Nav";
import Footer from "@/components/shared/Footer";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});
export const metadata = {
  title: "FF Tournament",
  description: "Generated by FF Tournament",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} bg-slate-900 text-white min-h-screen `}
      >
        <div className="bg-slate-950 min-h-screen container pt-2 relative">
          <Nav />
          {children}
          <Footer />
          <div className="modal"></div>
        </div>
      </body>
    </html>
  );
}
