import { Roboto } from "next/font/google";
import "./globals.css";
import Nav from "@/components/shared/Nav";
import Footer from "@/components/shared/Footer";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});

export const metadata = {
  title: "FF Tournament",
  description: "Generated by FF Tournament",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} bg-slate-900 text-white min-h-screen`}
      >
        <div className=" container w-full bg-custom-img bg-cover bg-no-repeat ">
          <div className="bg-black/50 min-h-screen relative">
            <Nav />
            <div className="pt-4 px-6">
              {children}
              <Footer />
            </div>
            <div className="modal"></div>
          </div>
        </div>
      </body>
    </html>
  );
}
